### PR TITLE
Fixes Issue#7 and layout renderer error

### PR DESCRIPTION
**Pull request by vedant1811**
Ref: https://github.com/DavidPacioianu/InkPageIndicator/issues/7

### CODE REVIEW

**Comment by DavidPacioianu** [comment]
This is great. Thank you!

**Comment by vedant1811** [comment]
@DavidPacioianu Welcome :)
When can I expect this to be in the gradle library?

**Comment by DavidPacioianu** [comment]
It is already on gradle.

**Comment by vedant1811** [comment]
Awesome! Will include it in my app

Regards,
Vedant.

**Pull request merged**
